"""
Django settings for cbs_cloud project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from datetime import timedelta
from dotenv import load_dotenv
from django.conf import settings
from rest_framework.settings import DEFAULTS, APISettings

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Load environment variables from .env file
load_dotenv()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY", "cvn=+yd^tcwebfwt$@8cp=&zjrcu!u5b2k5#m-)eq94j1ediuk"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True") == "True"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

# Application definition

# CORS configuration
CORS_ALLOWED_ORIGINS = os.getenv(
    "CORS_ALLOWED_ORIGINS", "http://localhost:8081,http://127.0.0.1:8081"
).split(",")

# Additional CORS settings for better compatibility
CORS_ALLOW_ALL_ORIGINS = os.getenv("CORS_ALLOW_ALL_ORIGINS", "True") == "True"
CORS_ALLOW_CREDENTIALS = os.getenv("CORS_ALLOW_CREDENTIALS", "True") == "True"

# Allow specific headers that might be needed
CORS_ALLOW_HEADERS = os.getenv(
    "CORS_ALLOW_HEADERS",
    "accept,accept-encoding,authorization,content-type,dnt,origin,user-agent,x-csrftoken,x-requested-with,token",
).split(",")

# Allow specific HTTP methods
CORS_ALLOWED_METHODS = os.getenv(
    "CORS_ALLOWED_METHODS", "DELETE,GET,OPTIONS,PATCH,POST,PUT"
).split(",")

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "cbs",
    "rest_framework",
    "rest_framework_api_key",
    "corsheaders",
    "rest_framework_simplejwt",  # required for simple JWT
    "django_extensions",
    "defects",
    "trains",
    "alerts",
    "notifications",
    "django_eventstream",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "request_logging.middleware.LoggingMiddleware",
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise middleware serves static files efficiently in production
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    #'cbs.server_timing.middleware.ServerTiming',
]
DJANGO_REQUEST_LOGGING_LOG_RESPONSE_DEFAULT_VALUE = False
ROOT_URLCONF = "cbs_cloud.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "cbs_cloud.wsgi.application"
STATIC_ROOT = "/app/static"


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
    }
}

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Authentication backends
AUTHENTICATION_BACKENDS = ("django.contrib.auth.backends.ModelBackend",)

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"


USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = os.getenv("STATIC_URL", "/static/")
MEDIA_URL = os.getenv("MEDIA_URL", "/media/")

# Use WhiteNoise staticfiles storage for efficient static file serving
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# required for simple JWT
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DATETIME_FORMAT": "%m/%d/%Y %H:%M:%S",
}

# JWT settings
# required for simple JWT
SIMPLE_JWT_SIGNING_KEY = os.getenv(
    "SIMPLE_JWT_SIGNING_KEY", "b=72^ado*%1(v3r7rga9ch)03xr=d*f)lroz94kosf!61((9=i"
)

# required for simple JWT
# SUPERUSER_TOKEN_LIFETIME: longer access token lifetime for (CC/Admin) superuser
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "SUPERUSER_TOKEN_LIFETIME": timedelta(days=365),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SIMPLE_JWT_SIGNING_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "JTI_CLAIM": "jti",
}

# required for simple JWT
USER_SETTINGS = getattr(settings, "JWT_AUTH", None)

# required for simple JWT
# List of settings that may be in string import notation.
IMPORT_STRINGS = (
    "JWT_ENCODE_HANDLER",
    "JWT_DECODE_HANDLER",
    "JWT_PAYLOAD_HANDLER",
    "JWT_PAYLOAD_GET_USER_ID_HANDLER",
    "JWT_PAYLOAD_GET_USERNAME_HANDLER",
    "JWT_RESPONSE_PAYLOAD_HANDLER",
    "JWT_GET_USER_SECRET_KEY",
    "JWT_DEVICES_RESPONSE_PAYLOAD_HANDLER",
    "JWT_DEVICES_PAYLOAD_HANDLER",
    "JWT_DEVICES_ENCODE_HANDLER",
    "JWT_DEVICES_DECODE_HANDLER",
)

# required for simple JWT
api_settings = APISettings(USER_SETTINGS, DEFAULTS, IMPORT_STRINGS)

#  (Docker mounts MEDIA_HOST_PATH to /app/media)
MEDIA_ROOT = "/app/media"
import os

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
        "request_format": {
            "format": "{levelname} {asctime} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": "./logs/django.log",
            "formatter": "verbose",
        },
        "request_file": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "./logs/requests.log",
            "maxBytes": 1024 * 1024 * 200,  # 200 MB
            "backupCount": 30,
            "formatter": "request_format",
        },
        "console": {"class": "logging.StreamHandler", "level": "INFO"},
    },
    "loggers": {
        "django": {
            "handlers": ["file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["request_file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "": {  # Root logger
            "handlers": ["console"],
            "level": "INFO",
        },
    },
}
USE_HTTPS = os.getenv("USE_HTTPS", "false").lower() == "true"

if USE_HTTPS:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True


DJANGO_EVENTSTREAM_ALLOWED_CHANNELS = [
    ("train-events", lambda _: True),  # allow all requests for 'train-events'
]


# Redis configuration for django-eventstream
# EVENTSTREAM_STORAGE_CLASS = 'django_eventstream.storage.RedisStorage'

# # Cache configuration for Redis connection
# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": "redis://redis:6379/1",  # 'redis' is the service name from docker-compose
#         "OPTIONS": {
#             "CLIENT_CLASS": "django_redis.client.DefaultClient",
#         }
#     }
# }

# # Disable persistent DB connections for gevent compatibility
# DATABASES['default']['CONN_MAX_AGE'] = 0

# # Keep this channel configuration
# DJANGO_EVENTSTREAM_ALLOWED_CHANNELS = [
#     ("train-events", lambda _: True),  # allow all requests for 'train-events'
# ]
