# Generated by Django 3.0.5 on 2025-07-13 17:48

import django.contrib.postgres.fields
from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DefectInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts", unixtimestampfield.fields.UnixTimeStampField(default=0.0)),
                ("train_id", models.CharField(max_length=100, null=True)),
                ("dpu_id", models.CharField(blank=True, max_length=20)),
                ("wagon_id", models.CharField(blank=True, max_length=100)),
                ("wagon_type", models.CharField(blank=True, max_length=100)),
                ("tagged_wagon_id", models.CharField(blank=True, max_length=30)),
                ("tagged_bogie_id", models.CharField(blank=True, max_length=30)),
                ("defect_code", models.CharField(max_length=30, null=True)),
                ("defect_image", models.ImageField(null=True, upload_to="images/")),
                ("side", models.CharField(max_length=30, null=True)),
                ("action_taken", models.CharField(max_length=255, null=True)),
                ("loco_no", models.CharField(max_length=30, null=True)),
                ("mvis_train_speed", models.FloatField()),
                ("mvis_total_axles", models.IntegerField()),
                ("dfis_train_id", models.CharField(max_length=30)),
                ("start_ts", unixtimestampfield.fields.UnixTimeStampField(default=0.0)),
                ("field_report", models.CharField(max_length=255, null=True)),
                ("remarks", models.CharField(max_length=255, null=True)),
            ],
            options={
                "db_table": "mvis_processed_info",
            },
        ),
        migrations.CreateModel(
            name="HealthInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts", unixtimestampfield.fields.UnixTimeStampField(default=0.0)),
                ("error_id", models.CharField(max_length=100, null=True)),
                ("error_severity", models.CharField(max_length=100, null=True)),
                ("error_desc", models.CharField(max_length=255, null=True)),
            ],
            options={
                "db_table": "health_info",
            },
        ),
        migrations.CreateModel(
            name="LeftWagonInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts", unixtimestampfield.fields.UnixTimeStampField(default=0.0)),
                ("train_id", models.CharField(max_length=100, null=True)),
                ("dpu_id", models.CharField(blank=True, max_length=20)),
                ("wagon_id", models.CharField(blank=True, max_length=100)),
                ("wagon_type", models.CharField(blank=True, max_length=100)),
                ("tagged_wagon_id", models.CharField(blank=True, max_length=30)),
                ("tagged_bogie_id", models.CharField(blank=True, max_length=30)),
                ("defect_code", models.CharField(max_length=30, null=True)),
                ("defect_image", models.ImageField(null=True, upload_to="images/")),
                ("side", models.CharField(max_length=30, null=True)),
                ("action_taken", models.CharField(max_length=255, null=True)),
            ],
            options={
                "db_table": "mvis_left_wagon_info",
            },
        ),
        migrations.CreateModel(
            name="MissedInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts", unixtimestampfield.fields.UnixTimeStampField(default=0.0)),
                ("train_id", models.CharField(max_length=100, null=True)),
                ("tagged_wagon_id", models.CharField(blank=True, max_length=30)),
                ("defect_code", models.CharField(max_length=30, null=True)),
                ("defect_image", models.ImageField(null=True, upload_to="images/")),
                ("missed_remarks", models.CharField(max_length=255, null=True)),
            ],
            options={
                "db_table": "mvis_unprocessed_info",
            },
        ),
        migrations.CreateModel(
            name="RightWagonInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts", unixtimestampfield.fields.UnixTimeStampField(default=0.0)),
                ("train_id", models.CharField(max_length=100, null=True)),
                ("dpu_id", models.CharField(blank=True, max_length=20)),
                ("wagon_id", models.CharField(blank=True, max_length=100)),
                ("wagon_type", models.CharField(blank=True, max_length=100)),
                ("tagged_wagon_id", models.CharField(blank=True, max_length=30)),
                ("tagged_bogie_id", models.CharField(blank=True, max_length=30)),
                ("defect_code", models.CharField(max_length=30, null=True)),
                ("defect_image", models.ImageField(null=True, upload_to="images/")),
                ("side", models.CharField(max_length=30, null=True)),
                ("action_taken", models.CharField(max_length=255, null=True)),
            ],
            options={
                "db_table": "mvis_right_wagon_info",
            },
        ),
        migrations.CreateModel(
            name="TrainConsolidatedInfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("train_id", models.CharField(max_length=30)),
                ("dfis_train_id", models.CharField(max_length=30)),
                ("train_type", models.CharField(max_length=100)),
                ("dpu_id", models.CharField(blank=True, max_length=20)),
                ("total_axles", models.IntegerField()),
                (
                    "entry_time",
                    unixtimestampfield.fields.UnixTimeStampField(default=0.0),
                ),
                (
                    "exit_time",
                    unixtimestampfield.fields.UnixTimeStampField(default=0.0),
                ),
                ("total_wheels", models.IntegerField()),
                ("total_bad_wheels", models.IntegerField()),
                ("direction", models.CharField(max_length=100)),
                ("train_speed", models.FloatField()),
                ("ilf_threshold_warning", models.FloatField(null=True)),
                ("ilf_threshold_critical", models.FloatField(null=True)),
                ("mdil_threshold_warning", models.FloatField(null=True)),
                ("mdil_threshold_critical", models.FloatField(null=True)),
                ("train_processed", models.BooleanField(default=True)),
                ("remark", models.CharField(default="None", max_length=255)),
            ],
            options={
                "db_table": "train_consolidated_info",
            },
        ),
        migrations.CreateModel(
            name="TrainInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts", unixtimestampfield.fields.UnixTimeStampField(default=0.0)),
                ("train_id", models.CharField(max_length=100, null=True)),
                ("vehicle_no", models.CharField(max_length=100, null=True)),
                ("vehicle_type", models.CharField(max_length=100, null=True)),
                ("train_direction", models.CharField(max_length=100, null=True)),
                ("train_speed", models.FloatField(null=True)),
                ("entry_ts", unixtimestampfield.fields.UnixTimeStampField(default=0.0)),
                ("exit_ts", unixtimestampfield.fields.UnixTimeStampField(default=0.0)),
            ],
            options={
                "db_table": "train_info",
            },
        ),
        migrations.CreateModel(
            name="TrainProcessedInfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ts", unixtimestampfield.fields.UnixTimeStampField(default=0.0)),
                ("train_id", models.CharField(max_length=30)),
                ("dpu_id", models.CharField(blank=True, max_length=20)),
                ("axle_id", models.IntegerField()),
                ("axle_speed", models.FloatField()),
                ("avg_dyn_load_left", models.FloatField(null=True)),
                ("avg_dyn_load_right", models.FloatField(null=True)),
                ("max_dyn_load_left", models.FloatField(null=True)),
                ("max_dyn_load_right", models.FloatField(null=True)),
                ("vertical_load_left", models.FloatField(null=True)),
                ("vertical_load_right", models.FloatField(null=True)),
                ("lateral_load_left", models.FloatField(null=True)),
                ("lateral_load_right", models.FloatField(null=True)),
                ("ilf_left", models.FloatField(null=True)),
                ("ilf_right", models.FloatField(null=True)),
                ("wheel_status_left", models.IntegerField(null=True)),
                ("wheel_status_right", models.IntegerField(null=True)),
                ("v1_fft_max_freq", models.IntegerField(null=True)),
                ("v1_fft_sd", models.FloatField(null=True)),
                ("v2_fft_max_freq", models.IntegerField(null=True)),
                ("v2_fft_sd", models.FloatField(null=True)),
                ("v3_fft_max_freq", models.IntegerField(null=True)),
                ("v3_fft_sd", models.FloatField(null=True)),
                ("v4_fft_max_freq", models.IntegerField(null=True)),
                ("v4_fft_sd", models.FloatField(null=True)),
                ("rake_id", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "db_table": "train_processed_info",
            },
        ),
        migrations.CreateModel(
            name="userDetails",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255, null=True)),
                ("password", models.CharField(max_length=255, null=True)),
                ("email", models.CharField(max_length=255, null=True)),
                ("phone", models.CharField(max_length=255, null=True)),
                ("firstname", models.CharField(max_length=255, null=True)),
                ("lastname", models.CharField(max_length=255, null=True)),
                (
                    "roles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            default="None", max_length=255, null=True
                        ),
                        size=None,
                    ),
                ),
                ("profile_image", models.ImageField(null=True, upload_to="images/")),
                ("active", models.BooleanField(null=True)),
            ],
            options={
                "db_table": "user_details",
            },
        ),
    ]
