# Generated by Django 4.2.23 on 2025-10-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="defectinfo",
            name="generated_by",
            field=models.CharField(
                choices=[("manual", "Manual"), ("system", "System")],
                default="system",
                help_text="Indicates whether the defect was generated manually or by system",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="defectinfo",
            name="is_deleted",
            field=models.BooleanField(
                default=False, help_text="Indicates whether the defect is deleted"
            ),
        ),
    ]
