# Generated by Django 4.2.23 on 2026-01-21 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("defects", "0007_defectinfo_alter_defectfeedbackattachment_id_and_more"),
        ("cbs", "0002_defectinfo_generated_by_defectinfo_is_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
            ],
            options={
                "db_table": "user_profile",
            },
        ),
        migrations.DeleteModel(
            name="RightWagonInfo",
        ),
        migrations.DeleteModel(
            name="TrainInfo",
        ),
        migrations.DeleteModel(
            name="TrainProcessedInfo",
        ),
        migrations.DeleteModel(
            name="userDetails",
        ),
        migrations.AlterField(
            model_name="healthinfo",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="leftwagoninfo",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="missedinfo",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
