# Generated by Django 3.0.5 on 2025-07-13 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DefectCategory",
            fields=[
                (
                    "category_code",
                    models.CharField(
                        max_length=10, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Defect Categories",
                "db_table": "defect_categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DefectType",
            fields=[
                (
                    "defect_code",
                    models.CharField(
                        max_length=10, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("multiplier_factor", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
                (
                    "category_code",
                    models.ForeignKey(
                        blank=True,
                        db_column="category_code",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="defect_types",
                        to="defects.DefectCategory",
                    ),
                ),
            ],
            options={
                "db_table": "defect_types",
                "ordering": ["defect_code"],
            },
        ),
    ]
