# Generated by Django 3.0.5 on 2025-07-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("defects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UniqueDefect",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("dpu_id", models.CharField(blank=True, max_length=255, null=True)),
                ("train_id", models.CharField(max_length=255)),
                ("wagon_id", models.CharField(blank=True, max_length=255, null=True)),
                ("wagon_type", models.CharField(blank=True, max_length=100, null=True)),
                ("loco_no", models.CharField(blank=True, max_length=100, null=True)),
                ("mvis_total_axles", models.IntegerField(blank=True, null=True)),
                ("mvis_train_speed", models.FloatField(blank=True, null=True)),
                (
                    "dfis_train_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("tagged_wagon_id", models.CharField(max_length=255)),
                (
                    "tagged_bogie_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("side", models.CharField(max_length=10)),
                ("defect_image", models.URLField(max_length=500)),
                ("defect_code", models.CharField(max_length=50)),
                (
                    "action_taken",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("start_ts", models.DateTimeField(blank=True, null=True)),
                ("field_report", models.TextField(blank=True, null=True)),
                ("ts", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Unique Defect",
                "verbose_name_plural": "Unique Defects",
                "db_table": "unique_defects",
                "managed": False,
            },
        ),
    ]
