# Generated by Django 4.2.23 on 2025-09-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("defects", "0002_uniquedefect"),
    ]

    operations = [
        migrations.CreateModel(
            name="Defects",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("train_id", models.CharField(max_length=20)),
                ("wagon_position", models.CharField(max_length=5)),
                ("wagon_no", models.CharField(max_length=20)),
                ("wagon_type", models.CharField(max_length=20)),
                ("side", models.CharField(max_length=5)),
                ("defect_image", models.URLField(max_length=100)),
                ("defect_code", models.CharField(max_length=10)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "field_report",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "action_taken",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("is_active", models.BooleanField()),
            ],
        ),
    ]
