# Generated by Django 4.2.23 on 2025-09-08 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("defects", "0003_defects"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="defects",
            table="defects",
        ),
    ]
