# Generated by Django 4.2.23 on 2025-09-17 15:40

import defects.utils
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("cbs", "0001_initial"),
        ("defects", "0004_alter_defects_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefectFeedbackAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=defects.utils.defect_feedback_upload_to),
                ),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "uuid_reference",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "defect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="cbs.defectinfo",
                    ),
                ),
            ],
            options={
                "db_table": "defect_feedback_attachment",
            },
        ),
    ]
