# Generated by Django 4.2.23 on 2025-10-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("defects", "0005_create_defect_feedback_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="defecttype",
            name="show_alert",
            field=models.BooleanField(default=True),
        ),
    ]
