# Generated by Django 4.2.23 on 2026-01-21 15:35

from django.db import migrations, models
import django.db.models.deletion
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("defects", "0006_defecttype_show_alert"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defectfeedbackattachment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="defects",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="defecttype",
            name="show_alert",
            field=models.BooleanField(
                default=True,
                help_text="Controls alert visibility for this component type",
            ),
        ),
        migrations.AlterField(
            model_name="defectfeedbackattachment",
            name="defect",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="cbs.defectinfo",
            ),
        ),
    ]
