# Generated by Django 4.2.23 on 2026-01-27 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("defects", "0007_defectinfo_alter_defectfeedbackattachment_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefectLocation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dpu_id", models.CharField(blank=True, max_length=20)),
                (
                    "defect_code",
                    models.ForeignKey(
                        blank=True,
                        db_column="defect_code",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="defect_locations",
                        to="defects.defecttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Defect Location",
                "verbose_name_plural": "Defect Locations",
                "db_table": "defect_locations",
                "unique_together": {("defect_code", "dpu_id")},
            },
        ),
    ]
